name: 'SSH Remote Commands'
description: 'Executing groovy scripts in a doker container'
author: 'Daniel Marthaler'
inputs:
  script:
    description: 'script'
    default: "-"

runs:
  using: 'composite'

  steps:

    - name: 'Run docker'
      id: run-docker
      shell: bash
      run: |
        printenv >> .env
        docker run --env-file .env \
        --rm \
        -e SCRIPT="${{ inputs.script }}" \
        -v "${{ github.workspace }}:/workspace" \
        ghcr.io/daniel-marthaler/plaintext-groovy-action:master