name: 'SSH Remote Commands'
description: 'Executing groovy scripts in a doker container'
author: 'Daniel Marthaler'
inputs:
  host:
    description: 'SSH host address.'
  port:
    description: 'SSH port number.'
    default: "22"
    
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'