name: 'SSH Remote Commands'
description: 'Executing groovy scripts in a doker container'
author: 'Daniel Marthaler'
inputs:
  host:
    description: 'host'
    default: "host"
  port:
    description: 'port'
    default: "22"
    
runs:
  using: 'docker'
  image: 'ghcr.io/daniel-marthaler/plaintext-groovy-action:master'

branding:
  icon: 'terminal'
  color: 'gray-dark'