name: 'SSH Remote Commands'
description: 'Executing groovy scripts in a doker container'
author: 'Daniel Marthaler'
inputs:
  host:
    description: 'host'
    default: "host"
  port:
    description: 'port'
    default: "22"

runs:
  using: 'composite'

  steps:

    - name: 'Run docker'
      id: run-docker
      shell:
      run: |

        docker run \
        --rm \
        -e SONAR_HOST_URL="a" \
        -e SONAR_SCANNER_OPTS="b" \
        -e SONAR_TOKEN="c" \
        -v "./:/data" \
        ghcr.io/daniel-marthaler/plaintext-groovy-action:master