name: deploy

on:
  push:
    branches:
      - master

permissions:
  packages: write
  contents: read

jobs:
  deployImage:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.read-targets.outputs.targets }}

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: 'Prepare'
        id: prep
        run: |
          chmod +x ./entrypoint.sh

      - name: Log in to the Container registry
        uses: docker/login-action@553b6f090f15b58451081ce157ff1929a266131d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@0f8c876bafbf5dbce05c36682ec68e9a0274a48a
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/plaintext-groovy-action
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@56932deb0a0db9d23e245320b1e45fec46b8d66f
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
