---
# date changed: 2.6.23
name: Integration
run-name: "Integration"
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  inte:
    uses: smc-org/pipeline-lib/.github/workflows/_main.yaml@release
    secrets: inherit
